apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - buildkit-build.yaml
  - forgejo-release.yaml
  - git-clone.yaml
  - image-exists.yaml
  - kustomize-deploy.yaml
  - manifest-create.yaml
  - openbao-kubernetes-login.yaml
