apiVersion: rules.alerting.grafana.app/v0alpha1
kind: AlertRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-kubernetes
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-kubernetes
  name: ar-c25b5bdba7eca2e4a136a523
spec:
  annotations:
    description: Based on recent sampling, the PersistentVolume claimed by {{
      $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} {{
      with $labels.cluster -}} on Cluster {{ . }} {{- end }} is expected to run
      out of inodes within four days. Currently {{ $value | humanizePercentage
      }} of its inodes are free.
    runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeinodesfillingup
    summary: PersistentVolumeInodes are filling up.
  execErrState: Error
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: |-
          (
            kubelet_volume_stats_inodes_free{job="integrations/kubernetes/kubelet"}
              /
            kubelet_volume_stats_inodes{job="integrations/kubernetes/kubelet"}
          ) < 0.15
          and
          kubelet_volume_stats_inodes_used{job="integrations/kubernetes/kubelet"} > 0
          and
          predict_linear(kubelet_volume_stats_inodes_free{job="integrations/kubernetes/kubelet"}[6h], 4 * 24 * 3600) < 0
          unless on(cluster, namespace, persistentvolumeclaim)
          kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
          unless on(cluster, namespace, persistentvolumeclaim)
          kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
        instant: false
        intervalMs: 1000
        maxDataPoints: 43200
        range: true
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
    B:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: B
        reducer: last
        settings:
          mode: dropNN
        type: reduce
      source: true
  for: 1h0m0s
  labels:
    severity: warning
  noDataState: OK
  title: KubePersistentVolumeInodesFillingUp
  trigger:
    interval: 1m
