apiVersion: rules.alerting.grafana.app/v0alpha1
kind: AlertRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-kubernetes
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-kubernetes
  name: ar-36f71bda9d42da99e3e1a4a4
spec:
  annotations:
    description: There are {{ $value }} different semantic versions of Kubernetes
      components running.
    runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeversionmismatch
    summary: Different semantic versions of Kubernetes components running.
  execErrState: Error
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: count by (cluster) (count by (git_version, cluster)
          (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"},"git_version","$1","git_version","(v[0-9]*.[0-9]*).*")))
          > 1
        instant: false
        intervalMs: 1000
        maxDataPoints: 43200
        range: true
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
    B:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: B
        reducer: last
        settings:
          mode: dropNN
        type: reduce
      source: true
  for: 15m0s
  labels:
    severity: warning
  noDataState: OK
  title: KubeVersionMismatch
  trigger:
    interval: 1m
