apiVersion: rules.alerting.grafana.app/v0alpha1
kind: RecordingRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-node
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-node
  name: rr-af6d105a2380680ea923a246
spec:
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: rate(node_disk_io_time_seconds_total{job=~"integrations/(node_exporter|unix)",
          device!=""}[5m])
        instant: true
        intervalMs: 1000
        maxDataPoints: 43200
        range: false
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
      source: true
  metric: instance_device:node_disk_io_time_seconds:rate5m
  targetDatasourceUID: mimir
  title: instance_device:node_disk_io_time_seconds:rate5m
  trigger:
    interval: 1m
