apiVersion: rules.alerting.grafana.app/v0alpha1
kind: AlertRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-mimir
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-mimir
  name: ar-a8a66182d52955150237bafb
spec:
  annotations:
    message: >
      Query-frontends and queriers are reporting different maximum supported
      query plan versions.
    runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimirqueryfrontendsandqueriersdisagreeonsupportedqueryplanversion
  execErrState: Error
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: >-
          # The label_replace calls below are so that we can match queriers with
          container labels like "ruler-querier" to

          # query-frontends with container labels like "ruler-query-frontend".

          # We support having the querier/query-frontend part as both a prefix
          and a suffix to support situations where the

          # query path name appears at the beginning (eg. "ruler-querier") or at
          the end (eg. "querier-mqe-test").


          min by (cluster, namespace, query_path) (
            label_replace(
              cortex_querier_maximum_supported_query_plan_version,
              "query_path", "$2", "container", "(querier)?-?(.*)-?(querier)?"
            )
          )

          !=

          min by (cluster, namespace, query_path) (
            label_replace(
              # Exclude the case where query-frontends failed to compute a maximum supported query plan version altogether (reporting -1), as
              # that is covered by the QueryFrontendNotComputingSupportedQueryPlanVersion alert.
              cortex_query_frontend_querier_ring_calculated_maximum_supported_query_plan_version != -1,
              "query_path", "$2", "container", "(query-frontend)?-?(.*)-?(query-frontend)?"
            )
          )
        instant: false
        intervalMs: 1000
        maxDataPoints: 43200
        range: true
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
    B:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: B
        reducer: last
        settings:
          mode: dropNN
        type: reduce
      source: true
  for: 15m0s
  labels:
    severity: warning
  noDataState: OK
  title: MimirQueryFrontendsAndQueriersDisagreeOnSupportedQueryPlanVersion
  trigger:
    interval: 1m
