apiVersion: rules.alerting.grafana.app/v0alpha1
kind: AlertRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-mimir
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-mimir
  name: ar-db76ef4cff77898a3f8e40be
spec:
  annotations:
    message: The Keda ScaledObject {{ $labels.scaledObject }} in {{
      $labels.namespace }} is experiencing errors.
    runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimirautoscalerkedafailing
  execErrState: Error
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: >-
          (
              # Find KEDA scalers reporting errors.
              label_replace(rate(keda_scaler_errors[5m]), "namespace", "$1", "exported_namespace", "(.*)")
              # Match only Mimir namespaces.
              * on(cluster, namespace) group_left max by(cluster, namespace) (cortex_build_info)
          )

          > 0
        instant: false
        intervalMs: 1000
        maxDataPoints: 43200
        range: true
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
    B:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: B
        reducer: last
        settings:
          mode: dropNN
        type: reduce
      source: true
  for: 1h0m0s
  labels:
    severity: critical
  noDataState: OK
  title: MimirAutoscalerKedaFailing
  trigger:
    interval: 1m
