apiVersion: rules.alerting.grafana.app/v0alpha1
kind: AlertRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-mimir
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-mimir
  name: ar-6640fee494ca4b8c3c35d159
spec:
  annotations:
    message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{
      $labels.namespace }} has not successfully cleaned up blocks in the last 6
      hours.
    runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorhasnotsuccessfullycleanedupblocks
  execErrState: Error
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: >-
          # The "last successful run" metric is updated even if the compactor
          owns no tenants,

          # so this alert correctly doesn't fire if compactor has nothing to do.

          (time() -
          cortex_compactor_block_cleanup_last_successful_run_timestamp_seconds >
          60 * 60 * 6)
        instant: false
        intervalMs: 1000
        maxDataPoints: 43200
        range: true
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
    B:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: B
        reducer: last
        settings:
          mode: dropNN
        type: reduce
      source: true
  for: 1h0m0s
  labels:
    severity: critical
  noDataState: OK
  title: MimirCompactorHasNotSuccessfullyCleanedUpBlocks
  trigger:
    interval: 1m
