apiVersion: rules.alerting.grafana.app/v0alpha1
kind: RecordingRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-mimir
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-mimir
  name: rr-4bd5a7f5e4990678ddb58f87
spec:
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: |-
          # Convenience rule to get the Memory request for both a deployment and a statefulset.
          # Multi-zone deployments are grouped together removing the "zone-X" suffix.
          # This recording rule is made compatible with the breaking changes introduced in kube-state-metrics v2
          # that remove resource metrics, ref:
          # - https://github.com/kubernetes/kube-state-metrics/blob/master/CHANGELOG.md#v200-alpha--2020-09-16
          # - https://github.com/kubernetes/kube-state-metrics/pull/1004
          #
          # This is the old expression, compatible with kube-state-metrics < v2.0.0,
          # where kube_pod_container_resource_requests_memory_bytes was removed:
          (
            sum by (cluster, namespace, deployment) (
              label_replace(
                label_replace(
                  kube_pod_container_resource_requests_memory_bytes,
                  "deployment", "$1", "pod", "(.*)-(?:([0-9]+)|([a-z0-9]+)-([a-z0-9]+))"
                ),
                # The question mark in "(.*?)" is used to make it non-greedy, otherwise it
                # always matches everything and the (optional) zone is not removed.
                "deployment", "$1", "deployment", "(.*?)(?:-zone-[a-z])?"
              )
            )
          )
          or
          # This expression is compatible with kube-state-metrics >= v1.4.0,
          # where kube_pod_container_resource_requests was introduced.
          (
            sum by (cluster, namespace, deployment) (
              label_replace(
                label_replace(
                  kube_pod_container_resource_requests{resource="memory"},
                  "deployment", "$1", "pod", "(.*)-(?:([0-9]+)|([a-z0-9]+)-([a-z0-9]+))"
                ),
                # The question mark in "(.*?)" is used to make it non-greedy, otherwise it
                # always matches everything and the (optional) zone is not removed.
                "deployment", "$1", "deployment", "(.*?)(?:-zone-[a-z])?"
              )
            )
          )
        instant: true
        intervalMs: 1000
        maxDataPoints: 43200
        range: false
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
      source: true
  metric: cluster_namespace_deployment:kube_pod_container_resource_requests_memory_bytes:sum
  targetDatasourceUID: mimir
  title: cluster_namespace_deployment:kube_pod_container_resource_requests_memory_bytes:sum
  trigger:
    interval: 1m
