apiVersion: rules.alerting.grafana.app/v0alpha1
kind: RecordingRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-mimir
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-mimir
  name: rr-0d6241d6f817ff298e62a0f2
spec:
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: histogram_quantile(0.99,
          sum(rate(cortex_querier_request_duration_seconds_bucket[1m])) by (le,
          cluster, job, route))
        instant: true
        intervalMs: 1000
        maxDataPoints: 43200
        range: false
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
      source: true
  metric: cluster_job_route:cortex_querier_request_duration_seconds:99quantile
  targetDatasourceUID: mimir
  title: cluster_job_route:cortex_querier_request_duration_seconds:99quantile
  trigger:
    interval: 1m
