{
 "title": "Strimzi Operators",
 "tags": [
  "kafka",
  "strimzi",
  "operators"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Infrastructure Cluster",
    "query": {
     "query": "label_values(up{job=~\"strimzi-(cluster|topic|user)-operator\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Kafka Namespace",
    "query": {
     "query": "label_values(strimzi_resource_state{cluster=~\"$cluster\",kind=\"Kafka\"},resource_namespace)"
    }
   },
   {
    "name": "kafka_cluster",
    "label": "Kafka Cluster",
    "query": {
     "query": "label_values(strimzi_resource_state{cluster=~\"$cluster\",kind=\"Kafka\",resource_namespace=~\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Operator Targets Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=~\"$cluster\",job=~\"strimzi-(cluster|topic|user)-operator\"})"
    }
   ]
  },
  {
   "title": "Kafka Resources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{cluster=~\"$cluster\",job=\"strimzi-cluster-operator\",kind=\"Kafka\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "KafkaTopic Resources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{cluster=~\"$cluster\",job=\"strimzi-topic-operator\",kind=\"KafkaTopic\",namespace=~\"$namespace\",selector=~\"strimzi.io/cluster=$kafka_cluster\"})"
    }
   ]
  },
  {
   "title": "Reconciliations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_successful_total{cluster=~\"$cluster\",job=~\"strimzi-(cluster|topic|user)-operator\",kind=~\"Kafka|KafkaTopic|KafkaNodePool\",namespace=~\"$namespace\"}[$__rate_interval])) by (job,kind)",
     "legendFormat": "{{job}} {{kind}} successful"
    },
    {
     "expr": "sum(increase(strimzi_reconciliations_failed_total{cluster=~\"$cluster\",job=~\"strimzi-(cluster|topic|user)-operator\",kind=~\"Kafka|KafkaTopic|KafkaNodePool\",namespace=~\"$namespace\"}[$__rate_interval])) by (job,kind)",
     "legendFormat": "{{job}} {{kind}} failed"
    }
   ]
  },
  {
   "title": "Maximum Reconciliation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "strimzi_reconciliations_duration_seconds_max{cluster=~\"$cluster\",job=~\"strimzi-(cluster|topic|user)-operator\",kind=~\"Kafka|KafkaTopic|KafkaNodePool\",namespace=~\"$namespace\"}",
     "legendFormat": "{{job}} {{kind}}"
    }
   ]
  },
  {
   "title": "Certificate Expiration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "min(strimzi_certificate_expiration_timestamp_ms{job=\"strimzi-cluster-operator\",k8s_cluster_name=~\"$cluster\",resource_namespace=~\"$namespace\",cluster=~\"$kafka_cluster\"}) by (cluster,type,resource_namespace)",
     "legendFormat": "{{resource_namespace}} {{cluster}} {{type}}"
    }
   ]
  },
  {
   "title": "Operator JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\",job=~\"strimzi-(cluster|topic|user)-operator\"}) by (job,area)",
     "legendFormat": "{{job}} {{area}}"
    }
   ]
  }
 ]
}