{
 "title": "Velero overview",
 "tags": [ "velero-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(velero_backup_attempt_total{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(velero_backup_attempt_total{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(velero_backup_attempt_total{}, instance)"
   },
   {
    "name": "schedule",
    "label": "Schedule",
    "query": "label_values(velero_backup_attempt_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}, schedule)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, cluster) (up{job=~\"$job\"})\n"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, cluster) (up{job=~\"$job\"})\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backup success rate (1 hour)",
   "type": "gauge",
   "description": "Success rate of backups within the instance in the past hour.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (label_replace(increase(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[1h]), \"schedule\", \"none\", \"schedule\", \"^$\") / label_replace(increase(velero_backup_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[1h]), \"schedule\", \"none\", \"schedule\", \"^$\") >  0)",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Restore success rate (1 hour)",
   "type": "gauge",
   "description": "Success rate of restores within the instance in the past hour.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (label_replace(increase(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[1h]), \"schedule\", \"none\", \"schedule\", \"^$\") / label_replace(increase(velero_restore_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[1h]), \"schedule\", \"none\", \"schedule\", \"^$\") >  0)",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Successful backups / $__interval ",
   "type": "stat",
   "description": "Number of successful backups.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__interval:]))",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "title": "Failed backups / $__interval ",
   "type": "stat",
   "description": "Number of failed backups.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__interval:]))",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "title": "Restore validation failure / $__interval ",
   "type": "stat",
   "description": "Number of failed restore validations.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(label_replace(velero_restore_validation_failed_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Backup validation failure / $__interval ",
   "type": "stat",
   "description": "Number of failed backup validations.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(label_replace(velero_backup_validation_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "failure"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Backup count / $__interval ",
   "type": "timeseries",
   "description": "Number of failed and successful backups.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(label_replace(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "increase(label_replace(velero_backup_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - failure"
    },
    {
     "expr": "increase(label_replace(velero_backup_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - attempt"
    }
   ]
  },
  {
   "title": "Backup success rate / $__interval",
   "type": "timeseries",
   "description": "Success rate of backups.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(label_replace(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__rate_interval:]) / clamp_min(rate(label_replace(velero_backup_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__rate_interval:]),1)",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup size",
   "type": "timeseries",
   "description": "Size of backups for this clusters given schedule.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(velero_backup_tarball_size_bytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup time",
   "type": "heatmap",
   "description": "The time it took to create backups.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(velero_backup_duration_seconds_bucket{le!=\"+Inf\", job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])) by (le)"
    }
   ]
  },
  { "title": "Restore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Restore count / $__interval ",
   "type": "timeseries",
   "description": "Number of failed and successful restores.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "increase(label_replace(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "increase(label_replace(velero_restore_failed_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - failure"
    },
    {
     "expr": "increase(label_replace(velero_restore_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - attempt"
    }
   ]
  },
  {
   "title": "Restore success rate / $__interval",
   "type": "timeseries",
   "description": "Success rate of restores.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(label_replace(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]) / clamp_min(increase(label_replace(velero_restore_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]),1)",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  { "title": "CSI snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CSI snapshot count / $__interval ",
   "type": "timeseries",
   "description": "Number of failed and successful CSI snapshots.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (schedule) (increase(label_replace(velero_csi_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "sum by (schedule) (increase(label_replace(velero_csi_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "{{schedule}} - failure"
    },
    {
     "expr": "sum by (schedule) (increase(label_replace(velero_csi_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]))",
     "legendFormat": "{{schedule}} - attempt"
    }
   ]
  },
  {
   "title": "CSI snapshot success rate / $__interval",
   "type": "timeseries",
   "description": "Success rate of CSI snapshots.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (schedule) (increase(label_replace(velero_csi_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]) / clamp_min(increase(label_replace(velero_csi_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]),1)) ",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  { "title": "Volume snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Volume snapshot count / $__interval ",
   "type": "timeseries",
   "description": "Number of failed and successful volume snapshots.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(label_replace(velero_volume_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "increase(label_replace(velero_volume_snapshot_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - failure"
    },
    {
     "expr": "increase(label_replace(velero_volume_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:])",
     "legendFormat": "{{schedule}} - attempt"
    }
   ]
  },
  {
   "title": "Volume snapshot success rate / $__interval",
   "type": "timeseries",
   "description": "Success rate of volume snapshots.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(label_replace(velero_volume_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]) / clamp_min(increase(label_replace(velero_volume_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}, \"schedule\", \"none\", \"schedule\", \"^$\")[$__interval:]),1)",
     "legendFormat": "{{schedule}}"
    }
   ]
  }
 ]
}