{
 "title": "Linux node / memory",
 "tags": [ "linux-node-integration" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "- Used: The amount of physical memory currently in use by the system.\n- Cached: The amount of physical memory used for caching data from disk. The Linux kernel uses available memory to cache data that is read from or written to disk. This helps speed up disk access times.\n- Free: The amount of physical memory that is currently not in use.\n- Buffers: The amount of physical memory used for temporary storage of data being transferred between devices or applications.\n- Available: The amount of physical memory that is available for use by applications. This takes into account memory that is currently being used for caching but can be freed up if needed.\n",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_Cached_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\n)\n",
     "legendFormat": "Memory used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory cached"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory available"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    }
   ]
  },
  { "title": "Vmstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory pages in / out",
   "type": "timeseries",
   "description": "Page-In - Return of pages to physical memory. This is a common and normal event.\n\nPage-Out - process of writing pages to disk. Unlike page-in, page-outs can indicate trouble.\nWhen the kernel detects low memory, it attempts to free memory by paging out. \nWhile occasional page-outs are normal, excessive and frequent page-outs can lead to thrashing.\nThrashing is a state in which the kernel spends more time managing paging activity than running applications, resulting in poor system performance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgpgin{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Page-In"
    },
    {
     "expr": "irate(node_vmstat_pgpgout{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Page-Out"
    }
   ]
  },
  {
   "title": "Memory pages swapping in / out",
   "type": "timeseries",
   "description": "Compared to the speed of the CPU and main memory, writing pages out to disk is relatively slow.\nNonetheless, it is a preferable option to crashing or killing off processes.\n\nThe process of writing pages out to disk to free memory is known as swapping-out.\nIf a page fault occurs because the page is on disk, in the swap area, rather than in memory,\nthe kernel will read the page back in from the disk to satisfy the page fault. \nThis is known as swapping-in.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "irate(node_vmstat_pswpin{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pages swapped in"
    },
    {
     "expr": "irate(node_vmstat_pswpout{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pages swapped out"
    }
   ]
  },
  {
   "title": "Memory page faults",
   "type": "timeseries",
   "description": "A page fault is an exception raised by the memory when a process accesses a memory page without the necessary preparations,\nrequiring a mapping to be added to the process's virtual address space.\n\nThe page contents may also need to be loaded from a backing store such as a disk.\nWhile the MMU detects the page fault, the operating system's kernel handles the exception by either making the required page accessible in physical memory or denying an illegal memory access.\nValid page faults are common and necessary to increase memory availability in any operating system that uses virtual memory, including Windows, macOS, and the Linux kernel.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgmajfault{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Major page fault operations"
    },
    {
     "expr": "irate(node_vmstat_pgfault{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n-\nirate(node_vmstat_pgmajfault{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "Minor page fault operations"
    }
   ]
  },
  {
   "title": "OOM Killer",
   "type": "timeseries",
   "description": "Out Of Memory killer is a process used by the Linux kernel when the system is running critically low on memory.\n\nThis can happen when the kernel has allocated more memory than is available for its processes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(node_vmstat_oom_kill{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "OOM killer invocations"
    }
   ]
  },
  { "title": "Memstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory active / inactive",
   "type": "timeseries",
   "description": "- Inactive: Memory which has been less recently used. It is more eligible to be reclaimed for other purposes.\n- Active: Memory that has been used more recently and usually not reclaimed unless absolutely necessary.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Memory active / inactive details",
   "type": "timeseries",
   "description": "- Inactive_file: File-backed memory on inactive LRU list.\n- Inactive_anon: Anonymous and swap cache on inactive LRU list, including tmpfs (shmem).\n- Active_file: File-backed memory on active LRU list.\n- Active_anon: Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Inactive_file"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Inactive_anon"
    },
    {
     "expr": "node_memory_Active_file_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Active_file"
    },
    {
     "expr": "node_memory_Active_anon_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Active_anon"
    }
   ]
  },
  {
   "title": "Memory commited",
   "type": "timeseries",
   "description": "- Committed_AS - Amount of memory presently allocated on the system.\n- CommitLimit - Amount of memory currently available to be allocated on the system.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Commited_AS"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "CommitLimit"
    }
   ]
  },
  {
   "title": "Memory shared and mapped",
   "type": "timeseries",
   "description": "- Mapped: This refers to the memory used in mapped page files that have been memory mapped, such as libraries.\n- Shmem: This is the memory used by shared memory, which is shared between multiple processes, including RAM disks.\n- ShmemHugePages: This is the memory used by shared memory and tmpfs allocated with huge pages.\n- ShmemPmdMapped: This is the amount of shared memory (shmem/tmpfs) backed by huge pages.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Mapped_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Shmem_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Shmem"
    },
    {
     "expr": "node_memory_ShmemPmdMapped_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "ShmemPmdMapped"
    },
    {
     "expr": "node_memory_ShmemHugePages_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "ShmemHugePages"
    }
   ]
  },
  {
   "title": "Memory writeback and dirty",
   "type": "timeseries",
   "description": "- Writeback: This refers to the memory that is currently being actively written back to the disk.\n- WritebackTmp: This is the memory used by FUSE for temporary writeback buffers.\n- Dirty: This type of memory is waiting to be written back to the disk.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Writeback"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "WritebackTmp"
    },
    {
     "expr": "node_memory_Dirty_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Dirty"
    }
   ]
  },
  {
   "title": "Memory Vmalloc",
   "type": "timeseries",
   "description": "Virtual Memory Allocation is a type of memory allocation in Linux that allows a process to request a contiguous block of memory larger than the amount of physically available memory. This is achieved by mapping the requested memory to virtual addresses that are backed by a combination of physical memory and swap space on disk.\n\n- VmallocChunk: Largest contiguous block of vmalloc area which is free.\n- VmallocTotal: Total size of vmalloc memory area.\n- VmallocUsed: Amount of vmalloc area which is used.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_VmallocChunk_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "VmallocChunk"
    },
    {
     "expr": "node_memory_VmallocTotal_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "VmallocTotal"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "VmallocUsed"
    }
   ]
  },
  {
   "title": "Memory slab",
   "type": "timeseries",
   "description": "Slab Allocation is a type of memory allocation in Linux that allows the kernel to efficiently manage the allocation and deallocation of small and frequently used data structures, such as network packets, file system objects, and process descriptors.\n\nThe Slab Allocator maintains a cache of pre-allocated objects of a fixed size and type, called slabs. When an application requests an object of a particular size and type, the Slab Allocator checks if a pre-allocated object of that size and type is available in the cache. If an object is available, it is returned to the application; if not, a new slab of objects is allocated and added to the cache.\n\n- SUnreclaim: Part of Slab, that cannot be reclaimed on memory pressure.\n- SReclaimable: Part of Slab, that might be reclaimed, such as caches.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SUnreclaim_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "SUnreclaim"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "SReclaimable"
    }
   ]
  },
  {
   "title": "Memory anonymous",
   "type": "timeseries",
   "description": "Memory Anonymous refers to the portion of the virtual memory that is used by a process for dynamically allocated memory that is not backed by any file or device.\n\nThis type of memory is commonly used for heap memory allocation, which is used by programs to allocate and free memory dynamically during runtime.\n\nMemory Anonymous is different from Memory Mapped files, which refer to portions of the virtual memory space that are backed by a file or device,\nand from Memory Shared with other processes,\nwhich refers to memory regions that can be accessed and modified by multiple processes.\n\n- AnonHugePages: Memory in anonymous huge pages.\n- AnonPages: Memory in user pages not backed by files.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_AnonHugePages_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "AnonHugePages"
    },
    {
     "expr": "node_memory_AnonPages_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "AnonPages"
    }
   ]
  },
  {
   "title": "Memory HugePages counter",
   "type": "timeseries",
   "description": "Huge Pages are a feature that allows for the allocation of larger memory pages than the standard 4KB page size. By using larger page sizes, the kernel can reduce the overhead associated with managing a large number of smaller pages, which can improve system performance for certain workloads.\n\n- HugePages_Free: Huge pages in the pool that are not yet allocated.\n- HugePages_Rsvd: Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made.\n- HugePages_Surp: Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "HugePages_Free"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "HugePages_Rsvd"
    },
    {
     "expr": "node_memory_HugePages_Surp{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "HugePages_Surp"
    }
   ]
  },
  {
   "title": "Memory HugePages size",
   "type": "timeseries",
   "description": "Huge Pages are a feature that allows for the allocation of larger memory pages than the standard 4KB page size. By using larger page sizes, the kernel can reduce the overhead associated with managing a large number of smaller pages, which can improve system performance for certain workloads.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Huge pages total size"
    },
    {
     "expr": "node_memory_Hugepagesize_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Huge page size"
    }
   ]
  },
  {
   "title": "Memory direct map",
   "type": "timeseries",
   "description": "Direct Map memory refers to the portion of the kernel's virtual address space that is directly mapped to physical memory. This mapping is set up by the kernel during boot time and is used to provide fast access to certain critical kernel data structures, such as page tables and interrupt descriptor tables.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_DirectMap1G_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "DirectMap1G"
    },
    {
     "expr": "node_memory_DirectMap2M_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "DirectMap2M"
    },
    {
     "expr": "node_memory_DirectMap4k_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "DirectMap4k"
    }
   ]
  },
  {
   "title": "Memory bounce",
   "type": "timeseries",
   "description": "Memory bounce is a technique used in the Linux kernel to handle situations where direct memory access (DMA) is required but the physical memory being accessed is not contiguous. This can happen when a device, such as a network interface card or a disk controller, requires access to a large amount of memory that is not available as a single contiguous block.\n\nTo handle this situation, the kernel uses a technique called memory bouncing. In memory bouncing, the kernel sets up a temporary buffer in physical memory that is large enough to hold the entire data block being transferred by the device. The data is then copied from the non-contiguous source memory to the temporary buffer, which is physically contiguous.\n\n- Bounce: Memory used for block device bounce buffers.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Bounce_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Bounce"
    }
   ]
  }
 ]
}