{
 "title": "Receiver",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(faro_receiver_logs_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_logs_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Measurements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_measurements_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_exceptions_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_events_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(faro_receiver_request_duration_seconds_count{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Rate Limited Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(faro_receiver_request_duration_seconds_count{status=\"429\", instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Processing errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_exporter_errors_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Sourcemaps Cached",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(faro_receiver_sourcemap_cache_size{instance=\"$instance\"})",
     "legendFormat": "sourcemaps cached"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(faro_receiver_request_duration_seconds_count{instance=\"$instance\", method=\"POST\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (instance) (increase(faro_receiver_request_duration_seconds_count{status=\"429\",instance=\"$instance\"}[5m]))",
     "legendFormat": "rate limited"
    },
    {
     "expr": "sum by(instance) (increase(faro_receiver_request_duration_seconds_count{status=~\"5.*\",instance=\"$instance\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Telemetry ingested",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_logs_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "logs"
    },
    {
     "expr": "sum(increase(faro_receiver_exceptions_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "exceptions"
    },
    {
     "expr": "sum(increase(faro_receiver_measurements_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "measurements"
    },
    {
     "expr": "sum(increase(faro_receiver_events_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "Exporter errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(faro_receiver_exporter_errors_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "exporter errors"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(faro_receiver_request_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval]))) / (sum(rate(faro_receiver_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(faro_receiver_request_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}