namespace: alerts-node-exporter-filesystem
groups:
  - name: node-exporter-filesystem
    rules:
      - alert: NodeFilesystemAlmostOutOfSpace
        expr: |
          (
            node_filesystem_avail_bytes{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} / node_filesystem_size_bytes{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} * 100 < 5
          and
            node_filesystem_readonly{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} == 0
          )
        for: 30m
        labels:
          severity: warning
        annotations:
          description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.
          summary: Filesystem has less than 5% space left.
      - alert: NodeFilesystemAlmostOutOfSpace
        expr: |
          (
            node_filesystem_avail_bytes{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} / node_filesystem_size_bytes{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} * 100 < 3
          and
            node_filesystem_readonly{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} == 0
          )
        for: 30m
        labels:
          severity: critical
        annotations:
          description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.
          summary: Filesystem has less than 3% space left.
      - alert: NodeFilesystemFilesFillingUp
        expr: |
          (
            node_filesystem_files_free{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} / node_filesystem_files{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} * 100 < 40
          and
            predict_linear(node_filesystem_files_free{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""}[6h], 24*60*60) < 0
          and
            node_filesystem_readonly{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} == 0
          )
        for: 1h
        labels:
          severity: warning
        annotations:
          description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up.
          summary: Filesystem is predicted to run out of inodes within the next 24 hours.
      - alert: NodeFilesystemFilesFillingUp
        expr: |
          (
            node_filesystem_files_free{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} / node_filesystem_files{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} * 100 < 20
          and
            predict_linear(node_filesystem_files_free{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""}[6h], 4*60*60) < 0
          and
            node_filesystem_readonly{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} == 0
          )
        for: 1h
        labels:
          severity: critical
        annotations:
          description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up fast.
          summary: Filesystem is predicted to run out of inodes within the next 4 hours.
      - alert: NodeFilesystemAlmostOutOfFiles
        expr: |
          (
            node_filesystem_files_free{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} / node_filesystem_files{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} * 100 < 5
          and
            node_filesystem_readonly{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} == 0
          )
        for: 1h
        labels:
          severity: warning
        annotations:
          description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left.
          summary: Filesystem has less than 5% inodes left.
      - alert: NodeFilesystemAlmostOutOfFiles
        expr: |
          (
            node_filesystem_files_free{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} / node_filesystem_files{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} * 100 < 3
          and
            node_filesystem_readonly{job=~"integrations/(node_exporter|unix)",fstype!="",mountpoint!=""} == 0
          )
        for: 1h
        labels:
          severity: critical
        annotations:
          description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left.
          summary: Filesystem has less than 3% inodes left.
