# Namespace: integrations-traefik
groups:
  - name: traefik
    rules:
      - alert: TraefikConfigReloadFailuresIncreasing
        expr: |
          sum by (job) (rate(traefik_config_reloads_failure_total{}[5m])) > 0
        for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Service
          asserts_severity: critical
          severity: critical
        annotations:
          description: |
            Traefik is failing to reload its config in {{ $labels.job }}.
          summary: Traefik is failing to reload its configuration.
      - alert: TraefikTLSCertificatesExpiring
        expr: |
          max by (instance, sans) ((last_over_time(traefik_tls_certs_not_after{}[5m]) - time()) / 86400) < 7
        for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Service
          asserts_severity: critical
          severity: critical
        annotations:
          description: |
            The minimum number of days until a Traefik-served certificate expires is {{ printf "%.0f" $value }} days on {{ $labels.sans }} which is below the critical threshold of 7.
          summary: A Traefik-served TLS certificate will expire very soon.
      - alert: TraefikTLSCertificatesExpiringSoon
        expr: |
          max by (instance, sans) ((last_over_time(traefik_tls_certs_not_after{}[5m]) - time()) / 86400) < 14 > 7
        for: 5m
        labels:
          asserts_alert_category: failure
          asserts_entity_type: Service
          asserts_severity: warning
          severity: warning
        annotations:
          description: |
            The minimum number of days until a Traefik-served certificate expires is {{ printf "%.0f" $value }} days on {{ $labels.sans }} which is less than 14 but greater than 7.
          summary: A Traefik-served TLS certificate will expire soon.
