apiVersion: rules.alerting.grafana.app/v0alpha1
kind: AlertRule
metadata:
  annotations:
    grafana.app/folder: alert-rules-traefik
    grafana.com/provenance: converted_prometheus
  labels:
    grafana.app/folder: alert-rules-traefik
  name: ar-fe96b4c57fa494b47f4a6253
spec:
  annotations:
    description: >
      The minimum number of days until a Traefik-served certificate expires is
      {{ printf "%.0f" $value }} days on {{ $labels.sans }} which is below the
      critical threshold of 7.
    summary: A Traefik-served TLS certificate will expire very soon.
  execErrState: Error
  expressions:
    A:
      datasourceUID: mimir
      model:
        datasource:
          type: prometheus
          uid: mimir
        expr: max by (instance, sans)
          ((last_over_time(traefik_tls_certs_not_after{}[5m]) - time()) / 86400)
          < 7
        instant: false
        intervalMs: 1000
        maxDataPoints: 43200
        range: true
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
    B:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: B
        reducer: last
        settings:
          mode: dropNN
        type: reduce
      source: true
  for: 5m0s
  labels:
    asserts_alert_category: failure
    asserts_entity_type: Service
    asserts_severity: critical
    severity: critical
  noDataState: OK
  title: TraefikTLSCertificatesExpiring
  trigger:
    interval: 1m
