name: Build Bitnami PostgreSQL DocumentDB

on:
  workflow_dispatch:
    inputs:
      bitnami_postgres_version:
        description: 'Bitnami PostgreSQL version'
        required: true
        default: '17.5.0-debian-12-r12'
      documentdb_version:
        description: 'DocumentDB version number'
        required: true
        default: '0.106.0'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/bitnami-postgres-documentdb
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bitnami-postgres-documentdb:${{ inputs.bitnami_postgres_version }}
          build-args: |
            BITNAMI_POSTGRES_VERSION=${{ inputs.bitnami_postgres_version }}
            DOCUMENTDB_VERSION=${{ inputs.documentdb_version }}