name: Build Firecrawl

on:
  workflow_dispatch:
    inputs:
      firecrawl_version:
        description: 'Firecrawl version tag'
        required: true
        default: 'v2.5.0'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Firecrawl repository
        uses: actions/checkout@v4
        with:
          repository: firecrawl/firecrawl
          ref: ${{ inputs.firecrawl_version }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/firecrawl:${{ inputs.firecrawl_version }}