name: Build OctoPrint Bambu

on:
  workflow_dispatch:
    inputs:
      octoprint_version:
        description: 'OctoPrint version to build'
        required: false
        default: 'latest'
        type: string
      bambu_plugin_branch:
        description: 'Bambu plugin branch/tag'
        required: false
        default: 'master'
        type: string
      bambu_plugin_repo:
        description: 'Bambu plugin repository URL'
        required: false
        default: 'https://github.com/jneilliii/OctoPrint-BambuPrinter'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: octoprint-bambu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build arguments
        id: build-args
        run: |
          OCTOPRINT_VERSION="${{ inputs.octoprint_version || 'latest' }}"
          BAMBU_PLUGIN_BRANCH="${{ inputs.bambu_plugin_branch || 'master' }}"
          BAMBU_PLUGIN_REPO="${{ inputs.bambu_plugin_repo || 'https://github.com/jneilliii/OctoPrint-BambuPrinter' }}"
          
          echo "octoprint-version=${OCTOPRINT_VERSION}" >> $GITHUB_OUTPUT
          echo "bambu-plugin-branch=${BAMBU_PLUGIN_BRANCH}" >> $GITHUB_OUTPUT
          echo "bambu-plugin-repo=${BAMBU_PLUGIN_REPO}" >> $GITHUB_OUTPUT

      - name: Generate custom tag
        id: custom-tag
        run: |
          OCTOPRINT_VERSION="${{ steps.build-args.outputs.octoprint-version }}"
          BAMBU_PLUGIN_BRANCH="${{ steps.build-args.outputs.bambu-plugin-branch }}"
          
          CUSTOM_TAG="${OCTOPRINT_VERSION}-${BAMBU_PLUGIN_BRANCH}"
          
          echo "custom-tag=${CUSTOM_TAG}" >> $GITHUB_OUTPUT
          echo "full-image-name=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${CUSTOM_TAG}" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/octoprint-bambu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.custom-tag.outputs.full-image-name }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            OCTOPRINT_VERSION=${{ steps.build-args.outputs.octoprint-version }}
            BAMBU_PLUGIN_BRANCH=${{ steps.build-args.outputs.bambu-plugin-branch }}
            BAMBU_PLUGIN_REPO=${{ steps.build-args.outputs.bambu-plugin-repo }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
 
      - name: Generate build summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **OctoPrint Version:** ${{ steps.build-args.outputs.octoprint-version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Bambu Plugin Branch:** ${{ steps.build-args.outputs.bambu-plugin-branch }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Bambu Plugin Repository:** ${{ steps.build-args.outputs.bambu-plugin-repo }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Custom Tag:** ${{ steps.custom-tag.outputs.custom-tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Full Image Name:** ${{ steps.custom-tag.outputs.full-image-name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Standard Tags:** ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY

