name: Publish LibreChat Helm Chart

on:
  workflow_dispatch:
    inputs:
      librechat_version:
        description: 'LibreChat version'
        required: true
        default: '1.8.9'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'
      
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Download LibreChat Helm Chart
        run: |
          wget https://github.com/danny-avila/LibreChat/releases/download/librechat-${{ inputs.librechat_version }}/librechat-${{ inputs.librechat_version }}.tgz
          
      - name: Extract and repackage chart
        run: |
          tar -xzf librechat-${{ inputs.librechat_version }}.tgz
          helm package librechat --version ${{ inputs.librechat_version }}
          
      - name: Push chart to GHCR
        run: |
          helm push librechat-${{ inputs.librechat_version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts